#!/usr/bin/env bash
# Web servers are the piece of software generating and
# Serving HTML pages, let’s install one!
#	Listens on port 80.
#	Returns a page containing "Hello World!" when queried
#	at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
